name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
  XUMM_TEST_BASE_URI: http://localhost:8080
  XUMM_API_KEY: aaaaaaaa-bbbb-cccc-dddd-1234567890ab
  XUMM_API_SECRET: cbbbbbbb-aaaa-cccc-dddd-1234567890ab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.17.1

      # Runs a single command using the runners shell
      - name: Install dependencies
        run: composer install

      # Runs a set of commands using the runners shell
      - name: Run tests
        run: make test
